const mongoose = require('mongoose');
const Schema = mongoose.Schema;

// Upon creating an invite, the Id generated by mLabs is sent in the res as the code to be used
// Once entered by the invited user, the server checks if the Invite is active, and that the user is not already in the team's userAccess array
// If approved, then the userId is added to the userAccess array and the Invite's active field is set to 'false'

const InviteSchema = new Schema({
  teamId: {
    type: String,
    required: true
  },
  creatorId: {
    type: String,
    required: true
  },
  active: {
    type: Boolean,
    required: true
  },
  date: {
    type: Date,
    default: Date.now
  }
});

module.exports = Invite = mongoose.model('invite', InviteSchema);